name: default-ml
channels:
  - defaults
dependencies:
  - ipykernel~=6.15.2
  - ipython~=7.31.1
  - numpy~=1.23.3
  - pandas~=1.4.4
  - pip~=22.2.2
  - python~=3.9.0
  - scikit-learn~=1.1.2
  - scipy~=1.9.1
  - pip:
    - kedro==0.18.3
    - kedro-docker==0.3.0
    - pytest-cov~=3.0
    - pytest-mock>=1.7.1, <2.0
    - pytest~=6.2 
    - seldon-core==1.14.1

