name: default-ml
channels:
  - defaults
dependencies:
  - ipykernel==6.17.1
  - ipython==7.34.0
  - numpy~=1.23.3
  - numpy-base~=1.23.3
  - pandas~=1.4.4
  - pip~=22.2.2
  - python~=3.9.0
  - scikit-learn~=1.1.2
  - scipy~=1.9.1
  - pip:
    - kedro==0.18.3
    - seldon-core==1.14.1
